import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:firebase_core/firebase_core.dart';

import 'package:brain_circle/auth/auth_gate.dart';
import 'package:brain_circle/auth/auth_controller.dart';
import 'package:brain_circle/auth/firebase_auth_repository.dart';
import 'package:brain_circle/homepage.dart';
import 'package:brain_circle/pages/focus_page.dart';
import 'package:brain_circle/utils/chronometer_notification.dart';
import 'package:brain_circle/utils/focus_timer.dart';
import 'firebase_options.dart'; // generated by FlutterFire CLI

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  await ChronometerNotification.initialize((action) {});

  // Make sure the default Firebase app exists before using FirebaseAuth
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  runApp(const MyApp());
}

class MyApp extends StatefulWidget {
  const MyApp({super.key});

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> with WidgetsBindingObserver {
  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addObserver(this);
  }

  @override
  void dispose() {
    WidgetsBinding.instance.removeObserver(this);
    super.dispose();
  }

  /// Handle app lifecycle changes to manage the focus timer and notification.
  /// Pauses the focus timer when the app is backgrounded unless the screen is locked or off.
  @override
  void didChangeAppLifecycleState(AppLifecycleState state) async {
    if (state == AppLifecycleState.paused) {
      final lockedOrOff = await ChronometerNotification.isScreenLockedOrOff();
      if (!lockedOrOff) {
        if (FocusTimer.instance.running.value) {
          await FocusTimer.instance.pause();
        } else {
          await ChronometerNotification.cancel();
        }
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: [
        ChangeNotifierProvider(
          create: (_) => AuthController(FirebaseAuthRepository()),
        ),
      ],
      child: MaterialApp(
        title: 'brain circle',
        theme: ThemeData(
          colorScheme: ColorScheme.fromSeed(seedColor: Colors.lightGreen),
        ),
        home: AuthGate(home: const Homepage()),
        routes: {
          '/homepage': (context) => const Homepage(),
          '/focus': (context) => const FocusPage(),
        },
      ),
    );
  }
}
